#!/bin/bash
myScript="${BASH_SOURCE:-$0}"
myDir=$(dirname $myScript)
myTop=$(readlink -f $myDir)
PYTHONHOME=$myDir/.. PYTHONPATH=$myDir/../lib/python2.7/site-packages:${PYTHONPATH} $myDir/python2 -S "$@"
