name: Build images for US AFs

on:
  push:
    branches:
      - "main"

jobs:
  build_base_images:
    name: Build base images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["centos7", "centos9", "cuda", "jupyter"]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2.1.0
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: "Build ${{ matrix.base }} base"
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:base"
          file: Dockerfile.${{matrix.base}}
          push: true
          tags: hub.opensciencegrid.org/usatlas/af_${{matrix.base}}:latest
          cache-from: type=${{ format('registry,ref=hub.opensciencegrid.org/usatlas/af_${{matrix.base}}/basecache',steps.extract_cache_name.outputs.cachetag) }}
          cache-to: type=${{ format('registry,ref=hub.opensciencegrid.org/usatlas/af_${{matrix.base}}/basecache',steps.extract_cache_name.outputs.cachetag) }},mode=max

  build_workflow_images:
    name: Build workflow images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["centos7", "centos9", "cuda", "jupyter"]
        workflow: ["tf"]
        #, "torch", "scikit", "root"]

    needs: build_base_images

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2.1.0
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Build ${{ matrix.base }} > ${{ matrix.workflow }}
        uses: docker/build-push-action@v3
        with:
          build-args: "BASE_IMAGE=hub.opensciencegrid.org/usatlas/af_${{ matrix.base }}"
          context: "{{defaultContext}}:base/workflow"
          file: Dockerfile.${{ matrix.workflow }}
          push: true
          tags: hub.opensciencegrid.org/usatlas/af_${{ matrix.base }}_${{ matrix.workflow }}:latest
          cache-from: type=${{ format('registry,ref=hub.opensciencegrid.org/usatlas/af_${{matrix.workflow}}/wfcache',steps.extract_cache_name.outputs.cachetag) }}
          cache-to: type=${{ format('registry,ref=hub.opensciencegrid.org/usatlas/af_${{matrix.workflow}}/wfcache',steps.extract_cache_name.outputs.cachetag) }},mode=max

  build_final_images:
    name: Build final images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["centos7", "centos9", "cuda", "jupyter"]
        workflow: ["tf"]
        # , "torch", "scikit", "root"]
        facility: ["uc", "bnl", "slac"]

    needs: build_workflow_images

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2.1.0
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Build Build ${{ matrix.base }} > ${{ matrix.workflow }} > ${{ matrix.facility }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE_IMAGE=hub.opensciencegrid.org/usatlas/af_${{ matrix.base }}_${{ matrix.workflow }}
            BASE=${{ matrix.base }}
          context: "{{defaultContext}}:base/workflow/af"
          file: Dockerfile.${{ matrix.facility }}
          push: true
          tags: hub.opensciencegrid.org/usatlas/af_${{ matrix.base }}_${{ matrix.workflow }}_${{ matrix.facility }}:latest
          cache-from: type=${{ format('registry,ref=hub.opensciencegrid.org/usatlas/af_${{matrix.facility}}/finalcache',steps.extract_cache_name.outputs.cachetag) }}
          cache-to: type=${{ format('registry,ref=hub.opensciencegrid.org/usatlas/af_${{matrix.facility}}/finalcache',steps.extract_cache_name.outputs.cachetag) }},mode=max
