name: Build images for US AFs

on:
  push:
    branches:
      - "main"

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Docker Build & Push Base image
  #       uses: mr-smithers-excellent/docker-build-push@master
  #       with:
  #         image: ivukotic/af_ml_base
  #         tags: latest, ${{ github.sha }}
  #         dockerfile: "Dockerfile.base"
  #         registry: docker.io
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  cuda:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2.1.0
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Build cuda base
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:base"
          file: Dockerfile.cuda
          push: true
          tags: hub.opensciencegrid.org/usatlas/af_cuda:latest

  cuda-tf:
    needs: cuda
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2.1.0
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Build cuda-tf
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:base/tf"
          file: Dockerfile.cuda-tf
          push: true
          tags: hub.opensciencegrid.org/usatlas/af_cuda_tf:latest

  cuda-tf-uc:
    needs: cuda-tf
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2.1.0
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Build base-tf-uc
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:base/tf/uc"
          file: Dockerfile.cuda-tf-uc
          push: true
          tags: hub.opensciencegrid.org/usatlas/af_cuda_tf_uc:latest
