ARG BASE_IMAGE=alpine:latest
FROM $BASE_IMAGE

LABEL maintainer Shuwei

ENV LD_LIBRARY_PATH=/usr/lib64
RUN if grep "centos" /etc/os-release; then \
       yum -y install tcsh; \
    fi

RUN echo "$BASE_IMAGE > BNL"